Repository knative-extensions/kn-plugin-operator, pull requests merged in 2021-12, with the labels that each got.

#36 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#38 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#40 Add the default value for InstallCmdFlags
  pkg/command/common/constants.go
  pkg/command/install/install.go
  pkg/command/install/install_test.go
Labels: lgtm, approved, size/M

#43 Add the function to check if the knative operator deployment exists
  pkg/command/common/deployment.go
Labels: lgtm, approved, size/M

#39 Make the kubeconfig configurable
  pkg/command/install/install.go
Labels: lgtm, approved, size/XS

#42 Add the yaml generator to convert operator crs into yaml
  go.mod
  go.sum
  pkg/command/common/yamlgenerator.go
  pkg/command/common/yamlgenerator_test.go
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#37 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#45 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#46 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#49 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#48 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#47 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/XS
