Repository knative-extensions/kn-plugin-operator, pull requests merged in 2021-11, with the labels that each got.

#18 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#19 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, approved, size/XS

#17 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/L, lgtm, approved

#22 Add some basic functions regarding files
  pkg/command/common/file.go
  pkg/command/common/file_test.go
  pkg/command/common/testdata/test.txt
  pkg/command/testingUtil/util.go
Labels: cla: yes, size/L, lgtm, approved

#23 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#24 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#27 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, approved, size/S

#28 [main] Update actions
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, approved, size/XS

#26 Add the module to handle the namespace resource
  go.mod
  pkg/command/common/namespace.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#31 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#30 Add the module to generate the download URL
  go.mod
  go.sum
  pkg/command/common/version.go
  pkg/command/common/version_test.go
  pkg/command/install/install.go
  pkg/command/install/install_test.go
  third_party/VENDOR-LICENSE/golang.org/x/mod/semver/LICENSE
  vendor/golang.org/x/mod/LICENSE
  vendor/golang.org/x/mod/PATENTS
  vendor/golang.org/x/mod/semver/semver.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/XL

#32 Implement the installation of the operator
  overlay/operator.yaml
  pkg/command/common/file.go
  pkg/command/common/namespace.go
  pkg/command/install/install.go
Labels: cla: yes, size/L, lgtm, approved

#33 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#34 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#35 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, lgtm, approved, size/XS
