Repository knative-extensions/kn-plugin-operator, pull requests merged in 2022-04, with the labels that each got.

#119 Add the integration tests for HA
  overlay/ke_deploy_label.yaml
  overlay/ke_resource_base.yaml
  overlay/ke_toleration.yaml
  overlay/ks_deploy_label.yaml
  overlay/ks_resource_base.yaml
  overlay/ks_toleration.yaml
  pkg/command/common/ytttag.go
  pkg/command/common/ytttag_test.go
  pkg/command/configure/deploymentlabel_test.go
  pkg/command/configure/ha.go
  pkg/command/configure/ha_test.go
  pkg/command/configure/manifests.go
  pkg/command/configure/resource_test.go
  pkg/command/configure/testdata/overlay/ke_deploy_label.yaml
  pkg/command/configure/testdata/overlay/ke_resource_base.yaml
  pkg/command/configure/testdata/overlay/ke_toleration.yaml
  pkg/command/configure/testdata/overlay/ks_deploy_label.yaml
  pkg/command/configure/testdata/overlay/ks_resource_base.yaml
  pkg/command/configure/testdata/overlay/ks_toleration.yaml
  pkg/command/configure/toleration_test.go
  test/e2e-tests.sh
  test/e2e/eventinghas_test.go
  test/e2e/servinghas_test.go
  test/resources/constants.go
  test/resources/verify.go
Labels: size/L, lgtm, approved

#112 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#121 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#123 Add the integration tests for image configuration
  pkg/command/configure/image.go
  pkg/command/configure/image_test.go
  test/e2e-tests.sh
  test/e2e/eventingimage_test.go
  test/e2e/servingimage_test.go
  test/resources/constants.go
  test/resources/verify.go
Labels: size/L, lgtm, approved

#116 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL

#124 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/knative.dev/operator/test/e2e-eventing-upgrade-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#126 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#125 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/L, lgtm, approved

#129 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#131 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#132 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#128 Update the int32 into *int32 for replicas
  go.mod
  go.sum
  test/resources/verify.go
  vendor/knative.dev/operator/pkg/apis/operator/base/common.go
  vendor/knative.dev/operator/pkg/apis/operator/base/zz_generated.deepcopy.go
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#130 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/knative.dev/operator/pkg/apis/operator/base/common.go
  vendor/knative.dev/operator/pkg/apis/operator/base/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/json/go.mod
  vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go
  vendor/sigs.k8s.io/json/internal/golang/encoding/json/kubernetes_patch.go
Labels: size/L, lgtm, approved

#133 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: lgtm, approved, size/XS

#134 Add support of service label and annotation overriding
  overlay/ke.yaml
  overlay/ke_cm_base.yaml
  overlay/ke_custom_manifests.yaml
  overlay/ke_deploy_label.yaml
  overlay/ke_image.yaml
  overlay/ke_replica.yaml
  overlay/ke_resource_base.yaml
  overlay/ke_source.yaml
  overlay/ke_toleration.yaml
  overlay/ks.yaml
  overlay/ks_cm_base.yaml
  overlay/ks_custom_manifests.yaml
  overlay/ks_deploy_label.yaml
  overlay/ks_image.yaml
  overlay/ks_ingress.yaml
  overlay/ks_istio_ns.yaml
  overlay/ks_replica.yaml
  overlay/ks_resource_base.yaml
  overlay/ks_toleration.yaml
  pkg/command/common/knative_operator.go
  pkg/command/common/kube_resource_test.go
  pkg/command/common/yamlgenerator_test.go
  pkg/command/configure/configmap_test.go
  pkg/command/configure/deploymentlabel.go
  pkg/command/configure/deploymentlabel_test.go
  pkg/command/configure/ha_test.go
  pkg/command/configure/image_test.go
  pkg/command/configure/manifests_test.go
  pkg/command/configure/resource_test.go
  pkg/command/configure/testdata/overlay/ke_cm_base.yaml
  pkg/command/configure/testdata/overlay/ke_custom_manifests.yaml
  pkg/command/configure/testdata/overlay/ke_deploy_label.yaml
  pkg/command/configure/testdata/overlay/ke_image.yaml
  pkg/command/configure/testdata/overlay/ke_replica.yaml
  pkg/command/configure/testdata/overlay/ke_resource_base.yaml
  pkg/command/configure/testdata/overlay/ke_toleration.yaml
  pkg/command/configure/testdata/overlay/ks_cm_base.yaml
  pkg/command/configure/testdata/overlay/ks_custom_manifests.yaml
  pkg/command/configure/testdata/overlay/ks_deploy_label.yaml
  pkg/command/configure/testdata/overlay/ks_image.yaml
  pkg/command/configure/testdata/overlay/ks_replica.yaml
  pkg/command/configure/testdata/overlay/ks_resource_base.yaml
  pkg/command/configure/testdata/overlay/ks_toleration.yaml
  pkg/command/configure/toleration_test.go
  pkg/command/install/testdata/overlay/ke.yaml
  pkg/command/install/testdata/overlay/ks.yaml
  pkg/command/install/testdata/overlay/ks_istio_ns.yaml
  pkg/command/uninstall/uninstall.go
  test/e2e-tests.sh
  test/e2e/eventingservicelabels_test.go
  test/e2e/servingservicelabels_test.go
  test/resources/verify.go
Labels: lgtm, approved, size/XL

#135 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/L, lgtm, approved

#136 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#137 Enable the service label and annotation overriding tests
  test/e2e-tests.sh
Labels: lgtm, approved, size/XS

#138 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#139 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
