Repository knative-extensions/kn-plugin-operator, pull requests merged in 2022-10, with the labels that each got.

#248 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#250 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#251 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#253 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/command/common/knative_operator.go
  pkg/command/remove/annotation.go
  pkg/command/remove/annotation_test.go
  pkg/command/remove/envvar.go
  pkg/command/remove/envvar_test.go
  pkg/command/remove/ha.go
  pkg/command/remove/ha_test.go
  pkg/command/remove/label.go
  pkg/command/remove/label_test.go
  pkg/command/remove/nodeselector.go
  pkg/command/remove/nodeselector_test.go
  pkg/command/remove/resource.go
  pkg/command/remove/resource_test.go
  pkg/command/remove/toleration.go
  pkg/command/remove/toleration_test.go
  test/resources/verify.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/operator/pkg/apis/operator/base/common.go
  vendor/knative.dev/operator/pkg/apis/operator/base/zz_generated.deepcopy.go
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#256 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#257 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
