Repository knative-extensions/kn-plugin-operator, pull requests merged in 2022-08, with the labels that each got.

#219 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#221 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#222 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#223 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#224 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#225 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS, skip-review

#226 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#228 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#227 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#229 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#231 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#234 Add the ingress flags into the install command
  pkg/command/configure/annotation.go
  pkg/command/configure/annotation_test.go
  pkg/command/configure/configmap.go
  pkg/command/configure/configmap_test.go
  pkg/command/configure/envvar.go
  pkg/command/configure/envvar_test.go
  pkg/command/configure/ha.go
  pkg/command/configure/ha_test.go
  pkg/command/configure/image.go
  pkg/command/configure/image_test.go
  pkg/command/configure/label.go
  pkg/command/configure/label_test.go
  pkg/command/configure/manifests.go
  pkg/command/configure/manifests_test.go
  pkg/command/configure/nodeselector.go
  pkg/command/configure/nodeselector_test.go
  pkg/command/configure/overlay/ke_cm_base.yaml
  pkg/command/configure/overlay/ke_custom_manifests.yaml
  pkg/command/configure/overlay/ke_deploy_label.yaml
  pkg/command/configure/overlay/ke_envvar.yaml
  pkg/command/configure/overlay/ke_image.yaml
  pkg/command/configure/overlay/ke_replica.yaml
  pkg/command/configure/overlay/ke_resource_base.yaml
  pkg/command/configure/overlay/ke_toleration.yaml
  pkg/command/configure/overlay/ks_cm_base.yaml
  pkg/command/configure/overlay/ks_custom_manifests.yaml
  pkg/command/configure/overlay/ks_deploy_label.yaml
  pkg/command/configure/overlay/ks_envvar.yaml
  pkg/command/configure/overlay/ks_image.yaml
  pkg/command/configure/overlay/ks_replica.yaml
  pkg/command/configure/overlay/ks_resource_base.yaml
  pkg/command/configure/overlay/ks_toleration.yaml
  pkg/command/configure/resource.go
  pkg/command/configure/resource_test.go
  pkg/command/configure/selector.go
  pkg/command/configure/selector_test.go
  pkg/command/configure/toleration.go
  pkg/command/configure/toleration_test.go
  pkg/command/enable/eventingsource.go
  pkg/command/enable/ingress.go
  pkg/command/enable/overlay/ke_source.yaml
  pkg/command/enable/overlay/ks_ingress.yaml
  pkg/command/install/install.go
  pkg/command/install/install_test.go
  pkg/command/install/overlay/ke.yaml
  pkg/command/install/overlay/ks.yaml
  pkg/command/install/overlay/ks_ingress.yaml
  pkg/command/install/overlay/ks_istio_ns.yaml
  pkg/command/install/overlay/operator.yaml
  pkg/command/install/overlay/operator_crds.yaml
  pkg/command/install/testdata/overlay/full_operator.yaml
  pkg/command/install/testdata/overlay/ks_ingress.yaml
  pkg/command/install/testdata/overlay/operator.yaml
Labels: lgtm, approved, size/XL
