Repository knative-extensions/kn-plugin-operator, pull requests merged in 2022-07, with the labels that each got.

#183 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#184 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#188 Add the tests to verify the deletion of image configuration
  test/e2e-tests.sh
  test/e2e/eventingimagedelete_test.go
  test/e2e/servingimagedelete_test.go
  test/resources/verify.go
Labels: size/L, lgtm, approved

#185 Add the integration tests on the removal of HA configuration
  test/e2e-tests.sh
  test/e2e/eventinghasdelete_test.go
  test/e2e/servinghasdelete_test.go
  test/resources/verify.go
Labels: size/L, lgtm, approved

#182 Add integration tests for the removal of env vars
  test/e2e-tests.sh
  test/e2e/eventingenvvardeletion_test.go
  test/e2e/servingenvvardelete_test.go
  test/resources/verify.go
Labels: size/L, lgtm, approved

#189 Remove the option of Natss as the the eventing source
  overlay/ke_source.yaml
  pkg/command/enable/eventingsource.go
  pkg/command/enable/eventingsource_test.go
Labels: lgtm, approved, size/S

#181 Remove the configuration of labels, annotations, selectors and node selectors
  pkg/command/common/knative_operator.go
  pkg/command/remove/annotation.go
  pkg/command/remove/annotation_test.go
  pkg/command/remove/label.go
  pkg/command/remove/label_test.go
  pkg/command/remove/nodeselector.go
  pkg/command/remove/nodeselector_test.go
  pkg/command/remove/remove.go
  pkg/command/remove/selector.go
  pkg/command/remove/selector_test.go
  test/e2e-tests.sh
  test/e2e/eventinglabelsdelete_test.go
  test/e2e/eventingservicelabelsdelete_test.go
  test/e2e/servinglabelsdelete_test.go
  test/e2e/servingservicelabelsdelete_test.go
  test/resources/verify.go
Labels: size/XXL, lgtm, approved

#190 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#194 Update the dependencies for 1.6 release
  go.mod
  go.sum
  test/resources/verify.go
  vendor/knative.dev/operator/pkg/apis/operator/base/common.go
  vendor/knative.dev/operator/pkg/apis/operator/base/zz_generated.deepcopy.go
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#197 Fix the installation issue of operator under a specific namespace
  overlay/operator.yaml
  pkg/command/install/install.go
  pkg/command/install/install_test.go
Labels: lgtm, approved, size/M

#198 Fix the eventing source issue with the command
  overlay/ke_source.yaml
  pkg/command/enable/enable.go
  pkg/command/enable/eventingsource.go
  pkg/command/enable/ingress.go
Labels: lgtm, approved, size/S

#202 Fix typo in root command display
  core/root.go
Labels: lgtm, approved, size/S

#205 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#207 Add the support of upgrading across multiple minor versions
  pkg/command/common/constants.go
  pkg/command/common/deployment.go
  pkg/command/install/install.go
  pkg/command/install/install_test.go
  test/e2e-tests.sh
Labels: lgtm, approved, size/XL

#209 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#214 update knative.dev/hack
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#213 Bump the golang version to 1.18
  .github/workflows/knative-boilerplate.yaml
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-version/go.mod
  vendor/github.com/BurntSushi/toml/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/hashicorp/go-version/go.mod
  vendor/github.com/imdario/mergo/go.mod
  vendor/github.com/imdario/mergo/go.sum
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/manifestival/client-go-client/go.mod
  vendor/github.com/manifestival/client-go-client/go.sum
  vendor/github.com/manifestival/manifestival/go.mod
  vendor/github.com/manifestival/manifestival/go.sum
  vendor/github.com/modern-go/reflect2/go.mod
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/go.opencensus.io/go.mod
  vendor/go.opencensus.io/go.sum
  vendor/go.uber.org/atomic/go.mod
  vendor/go.uber.org/atomic/go.sum
  vendor/go.uber.org/multierr/go.mod
  vendor/go.uber.org/multierr/go.sum
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/gomodules.xyz/jsonpatch/v2/go.mod
  vendor/gomodules.xyz/jsonpatch/v2/go.sum
  vendor/google.golang.org/appengine/go.mod
  vendor/google.golang.org/appengine/go.sum
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/json/go.mod
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
Labels: size/XXL, lgtm, approved

#212 Set the high-availability to empty instead of replicas
  pkg/command/remove/ha.go
  pkg/command/remove/ha_test.go
  test/e2e-tests.sh
  test/resources/verify.go
Labels: lgtm, approved, size/M

#216 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#218 Add the progress indicator to the installation
  go.mod
  go.sum
  pkg/command/install/install.go
  pkg/ui/progressindicator/progressindicator.go
  third_party/VENDOR-LICENSE/github.com/briandowns/spinner/LICENSE
  third_party/VENDOR-LICENSE/github.com/briandowns/spinner/NOTICE.txt
  third_party/VENDOR-LICENSE/github.com/fatih/color/LICENSE.md
  third_party/VENDOR-LICENSE/github.com/mattn/go-colorable/LICENSE
  third_party/VENDOR-LICENSE/github.com/mattn/go-isatty/LICENSE
  vendor/github.com/briandowns/spinner/.gitignore
  vendor/github.com/briandowns/spinner/.travis.yml
  vendor/github.com/briandowns/spinner/LICENSE
  vendor/github.com/briandowns/spinner/Makefile
  vendor/github.com/briandowns/spinner/NOTICE.txt
  vendor/github.com/briandowns/spinner/README.md
  vendor/github.com/briandowns/spinner/character_sets.go
  vendor/github.com/briandowns/spinner/spinner.go
  vendor/github.com/fatih/color/LICENSE.md
  vendor/github.com/fatih/color/README.md
  vendor/github.com/fatih/color/color.go
  vendor/github.com/fatih/color/doc.go
  vendor/github.com/mattn/go-colorable/LICENSE
  vendor/github.com/mattn/go-colorable/README.md
  vendor/github.com/mattn/go-colorable/colorable_appengine.go
  vendor/github.com/mattn/go-colorable/colorable_others.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-colorable/go.test.sh
  vendor/github.com/mattn/go-colorable/noncolorable.go
  vendor/github.com/mattn/go-isatty/LICENSE
  vendor/github.com/mattn/go-isatty/README.md
  vendor/github.com/mattn/go-isatty/doc.go
  vendor/github.com/mattn/go-isatty/go.test.sh
  vendor/github.com/mattn/go-isatty/isatty_bsd.go
  vendor/github.com/mattn/go-isatty/isatty_others.go
  vendor/github.com/mattn/go-isatty/isatty_plan9.go
  vendor/github.com/mattn/go-isatty/isatty_solaris.go
  vendor/github.com/mattn/go-isatty/isatty_tcgets.go
  vendor/github.com/mattn/go-isatty/isatty_windows.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved
