Repository knative-extensions/kn-plugin-operator, pull requests merged in 2022-01, with the labels that each got.

#51 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_random.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#50 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#53 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#55 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#52 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#54 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
Labels: lgtm, approved, size/S

#44 Add the support of installing serving and eventing
  overlay/ke.yaml
  overlay/ks.yaml
  overlay/ks_istio_ns.yaml
  pkg/command/common/deployment.go
  pkg/command/common/knative_operator.go
  pkg/command/install/install.go
  pkg/command/install/install_test.go
  pkg/command/install/testdata/overlay/ke.yaml
  pkg/command/install/testdata/overlay/ks.yaml
  pkg/command/install/testdata/overlay/ks_istio_ns.yaml
  pkg/command/install/testdata/overlay/operator.yaml
Labels: lgtm, approved, size/XL

#57 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#59 Implement the uninstallation of Knative operator and components
  pkg/command/uninstall/uninstall.go
Labels: size/L, lgtm, approved

#62 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/common.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#61 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#63 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#66 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M
