Repository knative-extensions/kn-plugin-operator, pull requests merged in 2022-03, with the labels that each got.

#86 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#88 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#87 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_386.go
  vendor/golang.org/x/sys/unix/syscall_linux_alarm.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_mipsx.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/syscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_386.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#90 Implement the configuration of HA replicas for Knative
  overlay/ke_replica.yaml
  overlay/ks_replica.yaml
  pkg/command/configure/configure.go
  pkg/command/configure/ha.go
  pkg/command/configure/ha_test.go
  pkg/command/configure/testdata/overlay/ke_replica.yaml
  pkg/command/configure/testdata/overlay/ks_replica.yaml
Labels: size/L, lgtm, approved

#89 Implement the configuration of ConfigMaps for Knative
  overlay/ke_cm_base.yaml
  overlay/ks_cm_base.yaml
  pkg/command/configure/configmap.go
  pkg/command/configure/configmap_test.go
  pkg/command/configure/configure.go
  pkg/command/configure/testdata/overlay/ke_cm_base.yaml
  pkg/command/configure/testdata/overlay/ks_cm_base.yaml
Labels: size/L, lgtm, approved

#91 Implement the label overriding for labels, annotations and nodeSelector in the deployment
  overlay/ke_deploy_label.yaml
  overlay/ks_deploy_label.yaml
  pkg/command/configure/configure.go
  pkg/command/configure/deploymentlabel.go
  pkg/command/configure/deploymentlabel_test.go
  pkg/command/configure/testdata/overlay/ke_deploy_label.yaml
  pkg/command/configure/testdata/overlay/ks_deploy_label.yaml
Labels: lgtm, approved, size/XL

#92 Implement the image overriding for knative
  overlay/ke_image.yaml
  overlay/ks_image.yaml
  pkg/command/configure/configure.go
  pkg/command/configure/image.go
  pkg/command/configure/image_test.go
  pkg/command/configure/testdata/overlay/ke_image.yaml
  pkg/command/configure/testdata/overlay/ks_image.yaml
Labels: size/L, lgtm, approved

#93 Add the module to update the configmaps and deployments for Knative
  pkg/command/common/kube_resource.go
  pkg/command/common/kube_resource_test.go
  pkg/command/testingUtil/util.go
Labels: lgtm, approved, size/XL

#95 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/M

#96 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#97 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/pkg/apis/operator/base/common.go
  vendor/knative.dev/operator/pkg/apis/operator/base/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#99 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#100 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/BurntSushi/toml/COPYING
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-version/CHANGELOG.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-version/constraint.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-version/version.go
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/auth/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/cert/OWNERS
  vendor/k8s.io/client-go/util/keyutil/OWNERS
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/kmeta/OWNERS
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/OWNERS
Labels: lgtm, approved, size/XL

#107 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#109 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: lgtm, approved, size/M

#108 Add integration tests for resource configurations
  pkg/command/configure/resource.go
  pkg/command/configure/resource_test.go
  test/e2e-tests.sh
  test/e2e/eventingresourceconfig_test.go
  test/e2e/servingresourceconfig_test.go
  test/resources/verify.go
Labels: size/L, lgtm, approved

#111 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/operator/pkg/client/clientset/versioned/typed/operator/v1alpha1/operator_client.go
  vendor/knative.dev/operator/pkg/client/clientset/versioned/typed/operator/v1beta1/operator_client.go
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#114 Add the integration tests for the label configuration
  pkg/command/configure/deploymentlabel.go
  pkg/command/configure/deploymentlabel_test.go
  test/e2e-tests.sh
  test/e2e/eventingannotation_test.go
  test/e2e/eventinglabels_test.go
  test/e2e/eventingnodeselector_test.go
  test/e2e/servingannotation_test.go
  test/e2e/servinglabels_test.go
  test/e2e/servingnodeselector_test.go
  test/resources/verify.go
Labels: size/L, lgtm, approved

#113 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/test/clients.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#115 Add the additional key-value pair into the test cases
  test/e2e-tests.sh
  test/e2e/eventingannotation_test.go
  test/e2e/eventinglabels_test.go
  test/e2e/eventingnodeselector_test.go
  test/e2e/servingannotation_test.go
  test/e2e/servinglabels_test.go
  test/e2e/servingnodeselector_test.go
  test/resources/constants.go
Labels: size/L, lgtm, approved

#118 Add the test cases to verify the configuration of ConfigMaps
  pkg/command/configure/configmap.go
  pkg/command/configure/configmap_test.go
  test/e2e-tests.sh
  test/e2e/eventingconfigmaps_test.go
  test/e2e/servingconfigmaps_test.go
  test/resources/verify.go
Labels: size/L, lgtm, approved
