Repository knative-extensions/kn-plugin-operator, pull requests merged in 2022-06, with the labels that each got.

#154 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#155 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#156 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#157 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#158 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#148 Improve the verification of the selector for services
  test/resources/verify.go
Labels: lgtm, approved, size/XS

#160 Remove the v1alpha1 CRD
  go.mod
  go.sum
  overlay/operator_crds.yaml
  pkg/command/install/install.go
  pkg/command/install/install_test.go
  pkg/command/install/testdata/overlay/full_operator.yaml
  pkg/command/install/testdata/overlay/operator_crds.yaml
  test/e2e-tests.sh
  test/e2e/operator_test.go
  vendor/knative.dev/operator/pkg/apis/operator/base/common.go
  vendor/knative.dev/operator/pkg/apis/operator/base/zz_generated.deepcopy.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/deploymentoverride.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/doc.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/istioconfig.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeeventing_conversion.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeeventing_types.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeserving_conversion.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeserving_types.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/register.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/operator/pkg/apis/operator/v1beta1/knativeeventing_types.go
  vendor/knative.dev/operator/pkg/apis/operator/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/operator/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/operator/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/operator/pkg/client/clientset/versioned/typed/operator/v1alpha1/doc.go
  vendor/knative.dev/operator/pkg/client/clientset/versioned/typed/operator/v1alpha1/generated_expansion.go
  vendor/knative.dev/operator/pkg/client/clientset/versioned/typed/operator/v1alpha1/knativeeventing.go
  vendor/knative.dev/operator/pkg/client/clientset/versioned/typed/operator/v1alpha1/knativeserving.go
  vendor/knative.dev/operator/pkg/client/clientset/versioned/typed/operator/v1alpha1/operator_client.go
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#163 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/multierr/LICENSE.txt
  vendor/go.uber.org/multierr/.travis.yml
  vendor/go.uber.org/multierr/CHANGELOG.md
  vendor/go.uber.org/multierr/LICENSE.txt
  vendor/go.uber.org/multierr/Makefile
  vendor/go.uber.org/multierr/README.md
  vendor/go.uber.org/multierr/error.go
  vendor/go.uber.org/multierr/go.mod
  vendor/go.uber.org/multierr/go.sum
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/global.go
  vendor/go.uber.org/zap/global_go112.go
  vendor/go.uber.org/zap/global_prego112.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/level.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/stacktrace.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/level.go
  vendor/go.uber.org/zap/zapcore/reflected_encoder.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#162 Implement the env var configuration
  overlay/ke_envvar.yaml
  overlay/ks_envvar.yaml
  pkg/command/configure/configure.go
  pkg/command/configure/envvar.go
  pkg/command/configure/envvar_test.go
  pkg/command/configure/testdata/overlay/ke_envvar.yaml
  pkg/command/configure/testdata/overlay/ks_envvar.yaml
  test/e2e-tests.sh
  test/e2e/eventingenvvar_test.go
  test/e2e/servingenvvar_test.go
  test/resources/constants.go
  test/resources/verify.go
Labels: lgtm, approved, size/XL

#164 Add the retry mechanism to apply the manifests
  pkg/command/common/knative_operator.go
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#166 Implement the deletion of resource configurations
  core/root.go
  pkg/command/common/knative_operator.go
  pkg/command/remove/remove.go
  pkg/command/remove/resource.go
  pkg/command/remove/resource_test.go
  test/e2e-tests.sh
  test/e2e/eventingresourcedelete_test.go
  test/e2e/servingresourcedelete_test.go
  test/resources/verify.go
Labels: lgtm, approved, size/XL

#168 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#169 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/pkg/client/clientset/versioned/clientset.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#171 Add the release scripts
  hack/global_vars.sh
  hack/release.sh
Labels: lgtm, approved, size/M

#172 Add the support of removing the toleration configurations
  pkg/command/remove/remove.go
  pkg/command/remove/toleration.go
  pkg/command/remove/toleration_test.go
  test/e2e-tests.sh
  test/e2e/eventingtolerationdelete_test.go
  test/resources/verify.go
Labels: size/L, lgtm, approved

#173 Add the test case for serving to verify if the toleration is deleted
  test/e2e-tests.sh
  test/e2e/servingtolerationdelete_test.go
  test/resources/verify.go
Labels: lgtm, approved, size/M

#174 Remove the image configuration with CLI for the operator
  pkg/command/common/knative_operator.go
  pkg/command/remove/image.go
  pkg/command/remove/image_test.go
  pkg/command/remove/remove.go
Labels: size/L, lgtm, approved

#176 Remove the configuration of env vars
  pkg/command/remove/envvar.go
  pkg/command/remove/envvar_test.go
  pkg/command/remove/remove.go
Labels: size/L, lgtm, approved

#177 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#175 Add the removal of HA configuration
  pkg/command/common/knative_operator.go
  pkg/command/remove/ha.go
  pkg/command/remove/ha_test.go
  pkg/command/remove/remove.go
Labels: size/L, lgtm, approved

#178 Refactor the annotation configuration
  pkg/command/common/flags.go
  pkg/command/configure/annotation.go
  pkg/command/configure/annotation_test.go
  pkg/command/configure/configure.go
  pkg/command/configure/label.go
  pkg/command/configure/label_test.go
  pkg/command/configure/nodeselector.go
  pkg/command/configure/nodeselector_test.go
  pkg/command/configure/selector.go
  pkg/command/configure/selector_test.go
  test/e2e-tests.sh
  test/e2e/eventinglabels_test.go
  test/e2e/eventingservicelabels_test.go
  test/e2e/servinglabels_test.go
  test/e2e/servingservicelabels_test.go
  test/resources/verify.go
Labels: size/XXL, lgtm, approved

#179 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#180 Refactor the validation methods
  pkg/command/configure/annotation.go
  pkg/command/configure/annotation_test.go
  pkg/command/configure/label.go
  pkg/command/configure/label_test.go
  pkg/command/configure/nodeselector.go
  pkg/command/configure/nodeselector_test.go
  pkg/command/configure/selector.go
  pkg/command/configure/selector_test.go
Labels: size/L, lgtm, approved
