Repository knative-extensions/kn-plugin-operator, pull requests merged in 2022-02, with the labels that each got.

#64 [main] Update actions
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
Labels: lgtm, approved, size/M

#67 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/pkg/apis/operator/base/common.go
  vendor/knative.dev/operator/pkg/apis/operator/base/doc.go
  vendor/knative.dev/operator/pkg/apis/operator/base/zz_generated.deepcopy.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeeventing_types.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeserving_types.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#68 Added the support of enabling ingresses
  core/root.go
  overlay/ks_ingress.yaml
  pkg/command/common/constants.go
  pkg/command/common/knative_operator.go
  pkg/command/common/namespace.go
  pkg/command/enable/enable.go
  pkg/command/enable/eventingsource.go
  pkg/command/enable/ingress.go
  pkg/command/enable/ingress_test.go
  pkg/command/install/install.go
  pkg/command/uninstall/uninstall.go
Labels: size/L, lgtm, approved

#65 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#70 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#71 Add the support to install eventing sources
  overlay/ke_source.yaml
  pkg/command/enable/eventingsource.go
  pkg/command/enable/eventingsource_test.go
  pkg/command/enable/ingress.go
  pkg/command/enable/ingress_test.go
Labels: size/L, lgtm, approved

#72 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#76 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/pkg/apis/operator/register.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/deploymentoverride.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/istioconfig.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeeventing_conversion.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeserving_conversion.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/register.go
  vendor/knative.dev/operator/pkg/apis/operator/v1beta1/knativeeventing_conversion.go
  vendor/knative.dev/operator/pkg/apis/operator/v1beta1/knativeeventing_lifecycle.go
  vendor/knative.dev/operator/pkg/apis/operator/v1beta1/knativeserving_conversion.go
  vendor/knative.dev/operator/pkg/apis/operator/v1beta1/knativeserving_lifecycle.go
  vendor/knative.dev/operator/pkg/apis/operator/v1beta1/register.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#77 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#78 Implement the resource configuration
  core/root.go
  overlay/ke_resource_base.yaml
  overlay/ks_resource_base.yaml
  pkg/command/common/constants.go
  pkg/command/common/constants_test.go
  pkg/command/common/knative_operator.go
  pkg/command/common/ytttag.go
  pkg/command/common/ytttag_test.go
  pkg/command/configure/configure.go
  pkg/command/configure/resource.go
  pkg/command/configure/resource_test.go
  pkg/command/configure/testdata/overlay/ke_resource_base.yaml
  pkg/command/configure/testdata/overlay/ks_resource_base.yaml
  pkg/command/enable/eventingsource_test.go
Labels: lgtm, approved, size/XL

#79 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#81 Implement the configuration of tolerations for the deployment
  overlay/ke_toleration.yaml
  overlay/ks_toleration.yaml
  pkg/command/common/strings.go
  pkg/command/common/strings_test.go
  pkg/command/configure/configure.go
  pkg/command/configure/resource.go
  pkg/command/configure/resource_test.go
  pkg/command/configure/testdata/overlay/ke_toleration.yaml
  pkg/command/configure/testdata/overlay/ks_toleration.yaml
  pkg/command/configure/toleration.go
  pkg/command/configure/toleration_test.go
Labels: lgtm, approved, size/XL

#82 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/operator/pkg/apis/operator/base/common.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeeventing_conversion.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeserving_conversion.go
  vendor/knative.dev/pkg/apis/url.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#83 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/XS

#84 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/istioconfig.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeeventing_conversion.go
  vendor/knative.dev/operator/pkg/apis/operator/v1alpha1/knativeserving_conversion.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#85 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/LICENSE
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/value/name.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/term.go
  vendor/modules.txt
Labels: size/L, lgtm, approved
