Repository knative-extensions/kn-plugin-operator, pull requests merged in 2023-04, with the labels that each got.

#279 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#280 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#281 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#282 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#274 [release-1.7] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/load.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#276 build arm64 darwin binaries
  hack/release.sh
Labels: lgtm, approved, size/XS, kind/enhancement

#285 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#286 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
