Repository knative-extensions/kn-plugin-operator, pull requests merged in 2023-02, with the labels that each got.

#269 Update the deps for 1.9 release
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#271 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#272 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#275 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
