Repository knative-extensions/kn-plugin-operator, pull requests merged in 2024-10, with the labels that each got.

#354 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#355 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#358 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#357 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/operator/pkg/apis/operator/base/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#360 Updated the operator lib for 1.16 release
  go.mod
  go.sum
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#361 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#362 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#363 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M
