Repository knative-extensions/kn-plugin-operator, pull requests merged in 2025-01, with the labels that each got.

#368 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#372 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#373 Updated the version of Knative Operator
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/operator/test/e2e-common.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#374 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#376 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
